export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCEED = 'FETCH_POSTS_SUCCEED';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const FETCH_POST_DETAIL_SUCCEED = 'FETCH_POST_DETAIL_SUCCEED';
export const FETCH_POST_DETAIL_FAILED = 'FETCH_POST_DETAIL_FAILED';
